---
- hosts: all


  tasks:

  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
     chdir: /opt/docker


  - name: create tag to image
    command: docker tag simple-devops-image ssingha/simple-devops-image

  - name: push image to dockerhub
    command: docker push ssingha/simple-devops-image

  - name: remove docker images from ansible server
    command: docker rmi simple-devops-image:latest ssingha/simple-devops-image
    ignore_errors: yes

